#!/bin/sh -ex
cp /var/lib/nodepool/.ssh/zuul_rsa.pub $TMP_HOOKS_PATH/zuul_rsa.pub

# To be removed after the 3.0 release
if [ -f /var/lib/nodepool/.ssh/jenkins_rsa.pub ]; then
    cat /var/lib/nodepool/.ssh/jenkins_rsa.pub >> $TMP_HOOKS_PATH/zuul_rsa.pub
fi
