#!/bin/sh -ex

groupadd -r zuul
useradd -r -g zuul -G zuul -d /var/lib/zuul -s /bin/bash -c "Zuul CI user" zuul

mkdir -p -m 0700 /var/lib/zuul/.ssh

if [ -f /tmp/in_target.d/nodepool_rsa.pub ]; then
    cat /tmp/in_target.d/nodepool_rsa.pub >> /var/lib/zuul/.ssh/authorized_keys
fi
cat /tmp/in_target.d/zuul_rsa.pub >> /var/lib/zuul/.ssh/authorized_keys

chmod 0600 /var/lib/zuul/.ssh/authorized_keys
chown -R zuul:zuul /var/lib/zuul

echo -e "Defaults    !requiretty\nzuul ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/zuul
