#!/bin/sh -ex
useradd -m -d /var/lib/jenkins -s /bin/bash jenkins
mkdir -m 0700 /var/lib/jenkins/.ssh
if [ -f /tmp/in_target.d/nodepool_rsa.pub ]; then
    cat /tmp/in_target.d/nodepool_rsa.pub >> /var/lib/jenkins/.ssh/authorized_keys
fi
cat /tmp/in_target.d/jenkins_rsa.pub >> /var/lib/jenkins/.ssh/authorized_keys
chmod 0600 /var/lib/jenkins/.ssh/authorized_keys
chown -R jenkins:jenkins /var/lib/jenkins
echo -e "Defaults    !requiretty\njenkins ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/jenkins
# Create /home/jenkins so that master can copy client jar
mkdir -m 0700 /home/jenkins
chown -R jenkins /home/jenkins
