#!/bin/bash -ex

yum install -y sf-config cloud-init cloud-utils-growpart

cat <<EOF> /tmp/ansible-install-playbook
- hosts: localhost
  connection: local
  roles:
    - name: "sf-base"
      action: "install"
    - name: "sf-install-server"
      action: "install"
    - name: "sf-mysql"
      action: "install"
    - name: "sf-rabbitmq"
      action: "install"
    - name: "sf-gateway"
      action: "install"
    - name: "sf-cauth"
      action: "install"
    - name: "sf-managesf"
      action: "install"
    - name: "sf-lecm"
      action: "install"
    - name: "sf-etherpad"
      action: "install"
    - name: "sf-lodgeit"
      action: "install"
    - name: "sf-gitweb"
      action: "install"
    - name: "sf-gerrit"
      action: "install"
    - name: "sf-gerritbot"
      action: "install"
    - name: "sf-jenkins"
      action: "install"
    - name: "sf-murmur"
      action: "install"
    - name: "sf-elasticsearch"
      action: "install"
    - name: "sf-job-logs-gearman-client"
      action: "install"
    - name: "sf-job-logs-gearman-worker"
      action: "install"
    - name: "sf-logstash"
      action: "install"
    - name: "sf-kibana"
      action: "install"
    - name: "sf-mirror"
      action: "install"
    - name: "sf-storyboard"
      action: "install"
    - name: "sf-storyboard-webclient"
      action: "install"
    - name: "sf-repoxplorer"
      action: "install"
    - name: "sf-firehose"
      action: "install"
    - name: "sf-logserver"
      action: "install"
    - name: "sf-zookeeper"
      action: "install"
    - name: "sf-nodepool"
      action: "install"
      nodepool_services: ['nodepool-launcher', 'nodepool-builder']
    - name: "sf-zuul"
      action: "install"
      zuul_services: ['zuul-server', 'zuul-merger', 'zuul-launcher']
    - name: "sf-mosquitto"
      action: "install"
    - name: "sf-ochlero"
      action: "install"
    - name: "sf-germqtt"
      action: "install"
EOF

[ -z "$DEBUG" ] || ansible_debug="-vvv"

ANSIBLE_CONFIG=/usr/share/sf-config/ansible/ansible.cfg ansible-playbook $ansible_debug /tmp/ansible-install-playbook
rm /tmp/ansible-install-playbook

yum update -y --exclude "jenkins"
