#!/bin/sh -ex
sudo cp /var/lib/nodepool/.ssh/id_rsa.pub $TMP_HOOKS_PATH/nodepool_rsa.pub

# To be removed after the 3.0 release
if [ -f /var/lib/nodepool/.ssh/jenkins_rsa.pub ]; then
    sudo cat /var/lib/nodepool/.ssh/jenkins_rsa.pub >> $TMP_HOOKS_PATH/nodepool_rsa.pub
fi
