#!/bin/sh -ex
if [ -f /var/lib/nodepool/.ssh/id_rsa.pub ]; then
    sudo cp /var/lib/nodepool/.ssh/id_rsa.pub $TMP_HOOKS_PATH/nodepool_rsa.pub
fi
if [ -f /var/lib/nodepool3/.ssh/id_rsa.pub ]; then
    sudo cp /var/lib/nodepool3/.ssh/id_rsa.pub $TMP_HOOKS_PATH/nodepool_rsa.pub
fi
