#!/bin/sh -ex
if [ -d /etc/nodepool/scripts ]; then
    sudo cp -a ${NODEPOOL_SCRIPTDIR:-/etc/nodepool/scripts} $TMP_MOUNT_PATH/opt/nodepool-scripts
fi
if [ -d /etc/opt/rh/rh-python35/nodepool/scripts ]; then
    sudo cp -a ${NODEPOOL_SCRIPTDIR:-/etc/opt/rh/rh-python35/nodepool/scripts} $TMP_MOUNT_PATH/opt/nodepool-scripts
fi

sudo chmod -R 0555 $TMP_MOUNT_PATH/opt/nodepool-scripts
