#!/bin/sh -ex
if grep -q "^zuul:" /etc/passwd; then
    usermod -a -G mock zuul
fi
if grep -q "^zuul-worker:" /etc/passwd; then
    usermod -a -G mock zuul-worker
fi
if grep -q "^jenkins:" /etc/passwd; then
    usermod -a -G mock jenkins
fi
