#!/bin/sh -ex

mkdir /usr/lib/selenium
curl -o /usr/lib/selenium/selenium-server.jar http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
pip install selenium pyvirtualdisplay
