#!/bin/sh -ex
if [ "z${SF_KEEP_RELEASE}" == "z" ]; then
    yum remove -y sf-release \
        centos-release-openstack-newton \
        centos-release-openstack-ocata \
        centos-release-openstack-pike \
        centos-release-qemu-ev \
        centos-release-virt-common \
        centos-release-opstools \
        centos-release-ceph-jewel \
        centos-release-storage-common
fi
